elasticsearch:
  image: ind3x/rpi-elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  restart: always
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  restart: always
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch

kibana:
  build: kibana/
  restart: always
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
